#include "web_server_module.h"
#include "web_ui.h"
#include "ap_setup.h"
#include "config.h"
#include "sensors.h"
#include "wifi_manager.h"
#include "ota_module.h"
#include "mqtt_module.h"
#include "telegram_module.h"
#include "sd_logger.h"
#include "runtime_settings.h"
#include "oled_display.h"
#include <WebServer.h>
#include <WebSocketsServer.h>
#include <ArduinoJson.h>
#include <Preferences.h>

namespace WebServerModule {

static WebServer        _http(WEB_PORT);
static WebSocketsServer _ws(WS_PORT);
static Preferences      _prefs;

// Captive portal redirect URL in PROGMEM (used in onNotFound + detection routes)
static const char CAPTIVE_URL[] PROGMEM = "http://" AP_IP_STR "/";

// ── AP Setup page ─────────────────────────────────────────

// ── WebSocket events ──────────────────────────────────────
static void _wsEvent(uint8_t num, WStype_t type, uint8_t* payload, size_t len) {
    if (type != WStype_TEXT) return;
    DynamicJsonDocument doc(256);
    if (deserializeJson(doc, payload, len) != DeserializationError::Ok) return;
    const char* cmd = doc["cmd"];
    if (!cmd) return;

    if (strcmp(cmd, "get_settings") == 0) {
        _prefs.begin("airmon", true);
        DynamicJsonDocument resp(1024);
        resp["type"]        = "settings";
        resp["ssid"]        = _prefs.getString("ssid","");
        resp["dev_name"]    = _prefs.getString("dev_name", DEVICE_NAME);
        resp["mqtt_en"]     = _prefs.getBool("mqtt_en",false);
        resp["mqtt_host"]   = _prefs.getString("mqtt_host","");
        resp["mqtt_port"]   = _prefs.getInt("mqtt_port", MQTT_DEFAULT_PORT);
        resp["mqtt_user"]   = _prefs.getString("mqtt_user","");
        resp["mqtt_topic"]  = _prefs.getString("mqtt_topic","airmonitor");
        resp["tg_en"]       = _prefs.getBool("tg_en",false);
        resp["tg_token"]    = _prefs.getString("tg_token","");
        resp["tg_chatid"]   = _prefs.getString("tg_chatid","");
        resp["ntp_srv"]     = _prefs.getString("ntp_srv", NTP_SERVER1);
        resp["tz_hours"]    = _prefs.getInt("tz_hours", TZ_OFFSET_SEC / 3600);
        resp["aht_temp_off"]= _prefs.getFloat("aht_temp_off", 0.0f);
        resp["aht_hum_off"] = _prefs.getFloat("aht_hum_off",  0.0f);
        // Thresholds
        resp["thr_co2"]     = _prefs.getInt("thr_co2",     ALERT_DEFAULT_CO2_PPM);
        resp["thr_tvoc"]    = _prefs.getInt("thr_tvoc",    ALERT_DEFAULT_TVOC_PPB);
        resp["thr_cooldown"]= _prefs.getInt("thr_cooldown",ALERT_DEFAULT_COOLDOWN_MIN);
        resp["thr_aqi"]     = _prefs.getInt("thr_aqi",        ALERT_DEFAULT_AQI);
        resp["thr_temp_hi"] = _prefs.getFloat("thr_temp_hi", ALERT_DEFAULT_TEMP_HI);
        resp["thr_hum_hi"]  = _prefs.getFloat("thr_hum_hi",  ALERT_DEFAULT_HUM_HI);
        auto cfg = RuntimeSettings::get();
        resp["csv_int_s"]   = cfg.csv_interval_sec;
        resp["hist24_min"]  = cfg.hist24_interval_min;
        resp["hist7_min"]   = cfg.hist7_interval_min;
        resp["hist30_min"]  = cfg.hist30_interval_min;
        resp["oled_en"]     = _prefs.getBool("oled_en", true);
        resp["debug_en"]    = _prefs.getBool("debug_en", false);
        _prefs.end();
        String out; serializeJson(resp, out);
        _ws.sendTXT(num, out);
    }
}

// ── CORS helper ───────────────────────────────────────────
static void _cors() { _http.sendHeader("Access-Control-Allow-Origin","*"); }

// ── Route registration ────────────────────────────────────
static void _registerRoutes() {

    // Main page
    _http.on("/", HTTP_GET, [](){
        _cors();
        if (WifiManager::currentMode() == WifiManager::Mode::AP) {
            // Serve AP setup page (gzip, generated by tools/build_web_ui.py)
            _http.sendHeader("Content-Encoding", "gzip");
            _http.sendHeader("Content-Length", String(AP_SETUP_HTML_GZ_LEN));
            _http.send_P(200, "text/html", (const char*)AP_SETUP_HTML_GZ, AP_SETUP_HTML_GZ_LEN);
        } else {
            // Serve dashboard (gzip, generated by tools/build_web_ui.py)
            _http.sendHeader("Content-Encoding", "gzip");
            _http.sendHeader("Content-Length", String(WEB_HTML_GZ_LEN));
            _http.sendHeader("Cache-Control", "no-cache");
            _http.send_P(200, "text/html", (const char*)WEB_HTML_GZ, WEB_HTML_GZ_LEN);
        }
    });

    // WiFi scan
    _http.on("/api/scan", HTTP_GET, [](){
        _cors();
        _http.send(200,"application/json",WifiManager::scanNetworks());
    });

    // Save WiFi credentials
    _http.on("/api/wifi", HTTP_POST, [](){
        _cors();
        DynamicJsonDocument doc(256);
        if (deserializeJson(doc,_http.arg("plain"))!=DeserializationError::Ok){
            _http.send(400,"text/plain","Bad JSON"); return;
        }
        String ssid=doc["ssid"].as<String>();
        String pass=doc["pass"].as<String>();
        _http.send(200,"text/plain","OK");
        delay(100);
        WifiManager::saveCredentials(ssid,pass);
    });

    // Save generic settings (MQTT, Telegram, debug)
    _http.on("/api/settings", HTTP_POST, [](){
        _cors();
        DynamicJsonDocument doc(768);
        if (deserializeJson(doc,_http.arg("plain"))!=DeserializationError::Ok){
            _http.send(400,"text/plain","Bad JSON"); return;
        }
        _prefs.begin("airmon",false);
        if(doc.containsKey("mqtt_en"))    _prefs.putBool("mqtt_en",   doc["mqtt_en"]);
        if(doc.containsKey("mqtt_host"))  _prefs.putString("mqtt_host",doc["mqtt_host"].as<String>());
        if(doc.containsKey("mqtt_port"))  _prefs.putInt("mqtt_port",  doc["mqtt_port"]);
        if(doc.containsKey("mqtt_user"))  _prefs.putString("mqtt_user",doc["mqtt_user"].as<String>());
        if(doc.containsKey("mqtt_pass"))  _prefs.putString("mqtt_pass",doc["mqtt_pass"].as<String>());
        if(doc.containsKey("mqtt_topic")) _prefs.putString("mqtt_topic",doc["mqtt_topic"].as<String>());
        if(doc.containsKey("tg_en"))      _prefs.putBool("tg_en",     doc["tg_en"]);
        if(doc.containsKey("tg_token"))   _prefs.putString("tg_token", doc["tg_token"].as<String>());
        if(doc.containsKey("tg_chatid"))  _prefs.putString("tg_chatid",doc["tg_chatid"].as<String>());
        if(doc.containsKey("dev_name"))   _prefs.putString("dev_name", doc["dev_name"].as<String>());
        if(doc.containsKey("ntp_srv"))     _prefs.putString("ntp_srv",      doc["ntp_srv"].as<String>());
        if(doc.containsKey("tz_hours"))    _prefs.putInt("tz_hours",         doc["tz_hours"]);
        if(doc.containsKey("aht_temp_off"))_prefs.putFloat("aht_temp_off",   doc["aht_temp_off"]);
        if(doc.containsKey("aht_hum_off")) _prefs.putFloat("aht_hum_off",    doc["aht_hum_off"]);
        if(doc.containsKey("csv_int_s"))  _prefs.putInt("csv_int_s",  doc["csv_int_s"]);
        if(doc.containsKey("hist24_min")) _prefs.putInt("hist24_min", doc["hist24_min"]);
        if(doc.containsKey("hist7_min"))  _prefs.putInt("hist7_min",  doc["hist7_min"]);
        if(doc.containsKey("hist30_min")) _prefs.putInt("hist30_min", doc["hist30_min"]);
        if(doc.containsKey("oled_en"))    _prefs.putBool("oled_en",   doc["oled_en"]);
        if(doc.containsKey("debug_en"))   _prefs.putBool("debug_en",  doc["debug_en"]);
        _prefs.end();
        RuntimeSettings::reload();
        MQTTModule::reload();
        TelegramModule::reload();
        if(doc.containsKey("aht_temp_off") || doc.containsKey("aht_hum_off"))
            Sensors::reloadOffsets();
        if(doc.containsKey("oled_en"))
            OLEDDisplay::enable(doc["oled_en"].as<bool>());
        if(doc.containsKey("debug_en"))
            g_debug_enabled = doc["debug_en"].as<bool>();
        _http.send(200,"text/plain","OK");
    });

    // Save alert thresholds
    _http.on("/api/thresholds", HTTP_POST, [](){
        _cors();
        DynamicJsonDocument doc(256);
        if (deserializeJson(doc,_http.arg("plain"))!=DeserializationError::Ok){
            _http.send(400,"text/plain","Bad JSON"); return;
        }
        uint16_t co2         = doc["co2"]      | ALERT_DEFAULT_CO2_PPM;
        uint16_t tvoc        = doc["tvoc"]     | ALERT_DEFAULT_TVOC_PPB;
        uint8_t  aqi         = doc["aqi"]      | ALERT_DEFAULT_AQI;
        float    tHi         = doc["temp"]     | ALERT_DEFAULT_TEMP_HI;
        float    hHi         = doc["hum"]      | ALERT_DEFAULT_HUM_HI;
        uint8_t  cooldownMin = doc["cooldown"] | ALERT_DEFAULT_COOLDOWN_MIN;
        TelegramModule::saveThresholds(co2, tvoc, aqi, tHi, hHi, cooldownMin);
        _http.send(200,"text/plain","OK");
    });

    // Get thresholds (for UI on load)
    _http.on("/api/thresholds", HTTP_GET, [](){
        _cors();
        auto t = TelegramModule::getThresholds();
        DynamicJsonDocument doc(128);
        doc["co2"]      = t.co2_ppm;
        doc["tvoc"]     = t.tvoc_ppb;
        doc["aqi"]      = t.aqi_level;
        doc["temp"]     = t.temp_hi;
        doc["hum"]      = t.hum_hi;
        doc["cooldown"] = t.cooldown_min;
        String out; serializeJson(doc,out);
        _http.send(200,"application/json",out);
    });

    // CSV export: /api/export?date=2026-04-10
    _http.on("/api/export", HTTP_GET, [](){
        _cors();
        String date = _http.arg("date");
        if (date.isEmpty()) {
            // Return list of available dates
            _http.send(200,"application/json",SDLogger::listLogDates());
            return;
        }
        // Stream the file
        if (!SDLogger::streamExport(date, &_http)) {
            _http.send(404,"text/plain","No log for date: "+date);
        }
    });

    // History endpoint — returns JSON array for chart pre-load
    // Served by AirMonitorPRO.ino via the global ring buffer
    // (registered externally after begin())

    // ENS160 calibration trigger
    _http.on("/api/calibrate", HTTP_POST, [](){
        _cors();
        bool ok = Sensors::calibrateBaseline();
        DynamicJsonDocument resp(128);
        resp["ok"]  = ok;
        resp["msg"] = Sensors::calibrateStatusMsg();
        String out; serializeJson(resp,out);
        _http.send(200,"application/json",out);
    });

    // Telegram test
    _http.on("/api/tg_test", HTTP_GET, [](){
        _cors();
        bool ok = TelegramModule::sendMessage(
            "✅ <b>Тест работает!</b>\nAir Monitor PRO на связи.");
        _http.send(200,"text/plain",ok?"OK":"FAIL — check token/chat_id");
    });

    // Reboot
    _http.on("/api/reboot", HTTP_POST, [](){
        _cors(); _http.send(200,"text/plain","Rebooting...");
        delay(300); ESP.restart();
    });

    // Factory reset
    _http.on("/api/reset", HTTP_POST, [](){
        _cors();
        WifiManager::factoryReset();
        _http.send(200,"text/plain","Reset done");
        delay(300); ESP.restart();
    });

    // Captive portal: redirect all unknown requests to setup page when in AP mode
    _http.onNotFound([](){
        if (WifiManager::currentMode() == WifiManager::Mode::AP) {
            _http.sendHeader("Location", FPSTR(CAPTIVE_URL), true);
            _http.send(302, "text/plain", "");
            return;
        }
        _http.send(404, "text/plain", "Not found");
    });

    // OS captive portal detection endpoints (iOS, Android, Windows, Firefox)
    auto _redir = [](){
        _http.sendHeader("Location", FPSTR(CAPTIVE_URL), true);
        _http.send(302, "text/plain", "");
    };
    _http.on("/generate_204",        HTTP_GET, _redir);
    _http.on("/gen_204",             HTTP_GET, _redir);
    _http.on("/hotspot-detect.html", HTTP_GET, _redir);
    _http.on("/connecttest.txt",     HTTP_GET, _redir);
    _http.on("/redirect",            HTTP_GET, _redir);
    _http.on("/ncsi.txt",            HTTP_GET, _redir);
    _http.on("/success.txt",         HTTP_GET, _redir);

    OTAModule::registerRoutes(_http);
}

// ─────────────────────────────────────────────────────────
void begin() {
    _ws.begin();
    _ws.onEvent(_wsEvent);
    _registerRoutes();
    _http.begin();
    DBGLN("[Web] HTTP:80 WS:81");
}

void loop() {
    _http.handleClient();
    _ws.loop();
}

// ── Register external route (used by main for /api/history) ──
void registerRoute(const String& path,
                   WebServer::THandlerFunction fn) {
    _http.on(path.c_str(), HTTP_GET, fn);
}

void broadcastData(const SensorData& d, const SystemStatus& s) {
    if (_ws.connectedClients() == 0) return;
    DynamicJsonDocument doc(768);
    doc["type"]       = "data";
    doc["temp"]       = d.temp;
    doc["hum"]        = d.hum;
    doc["co2"]        = d.co2;
    doc["tvoc"]       = d.tvoc;
    doc["aqi"]        = d.aqi;
    doc["rssi"]       = s.rssi;
    doc["sd"]         = s.sd_ok;
    doc["sd_used"]    = s.sd_used_mb;
    doc["sd_total"]   = s.sd_total_mb;
    doc["sd_pct"]     = s.sd_pct;
    doc["rtc"]        = s.rtc_ok;
    doc["ens"]        = s.ens_ok;
    doc["ens_status"] = Sensors::ensStatus();
    doc["aht"]        = s.aht_ok;
    doc["ip"]         = s.ip;
    doc["uptime"]     = s.uptime;
    doc["time_short"] = s.time_str;
    doc["date"]       = s.date_str;
    doc["ver"]        = FW_VERSION;
    doc["warmup"]     = s.ens_warmup;
    doc["warmup_pct"] = s.ens_warmup
        ? min(100.0f,(float)(millis()/(ENS160_WARMUP_MS/100.0f)))
        : 100.0f;
    doc["mqtt"]       = MQTTModule::isConnected();
    doc["tg"]         = TelegramModule::isEnabled();
    doc["hist24_rev"] = s.hist24_rev;
    doc["hist7_rev"]  = s.hist7_rev;
    doc["hist30_rev"] = s.hist30_rev;
    String out; serializeJson(doc,out);
    _ws.broadcastTXT(out);
}

void sendJSON(const String& json) {
    _http.sendHeader("Access-Control-Allow-Origin","*");
    _http.send(200,"application/json",json);
}

uint8_t connectedClients() {
    return _ws.connectedClients();
}

String arg(const String& name) {
    return _http.arg(name);
}
} // namespace WebServerModule
