#!/usr/bin/env python3
"""
build_web_ui.py  —  Minify + Gzip  web_ui.html and ap_setup.html → .h files
Run before every Arduino compile after editing either HTML file:
    python tools/build_web_ui.py       (Linux / macOS)
    tools\build_web_ui.bat             (Windows double-click)

No external dependencies — pure Python 3 stdlib.
"""

import gzip, re, sys, os

SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)


# ── Minifier ──────────────────────────────────────────────────────────────────
def minify(html: str) -> str:
    # Strip HTML comments (but not IE conditionals)
    html = re.sub(r'<!--(?!\[).*?-->', '', html, flags=re.DOTALL)

    # Minify <style> blocks
    def _css(m):
        css = m.group(1)
        css = re.sub(r'/\*.*?\*/', '', css, flags=re.DOTALL)
        css = re.sub(r'\s*([{};:,>+~])\s*', r'\1', css)
        css = re.sub(r'\s+', ' ', css).strip()
        return f'<style>{css}</style>'
    html = re.sub(r'<style>(.*?)</style>', _css, html,
                  flags=re.DOTALL | re.IGNORECASE)

    # Minify <script> blocks
    def _js(m):
        js = m.group(1)
        # Remove JS comments but not :// in URLs
        # First remove block comments
        js = re.sub(r'/\*.*?\*/', '', js, flags=re.DOTALL)
        # Remove line comments but preserve :// 
        js = re.sub(r'(?<!:)//[^\n]*', '', js)
        js = re.sub(r'\n\s*\n', '\n', js)
        js = re.sub(r'[ \t]+', ' ', js)
        js = re.sub(r'\n ', '\n', js).strip()
        return f'<script>{js}</script>'
    html = re.sub(r'<script>(.*?)</script>', _js, html,
                  flags=re.DOTALL | re.IGNORECASE)

    # Collapse whitespace between tags
    html = re.sub(r'>\s+<', '><', html)
    html = re.sub(r'\s{2,}', ' ', html)
    return html.strip()


# ── Writer ────────────────────────────────────────────────────────────────────
def build_one(src_path: str, dst_path: str,
              array_name: str, len_name: str) -> None:
    if not os.path.exists(src_path):
        print(f"WARNING: {src_path} not found — skipping")
        return

    with open(src_path, 'r', encoding='utf-8') as f:
        src = f.read()

    mini      = minify(src)
    gz        = gzip.compress(mini.encode('utf-8'), compresslevel=9)
    orig_kb   = len(src)  / 1024
    mini_kb   = len(mini) / 1024
    gz_kb     = len(gz)   / 1024
    saved_pct = 100 - int(len(gz) * 100 / len(src))

    # Format as C byte array, 16 bytes per line
    rows = []
    for i in range(0, len(gz), 16):
        chunk = gz[i:i+16]
        rows.append('  ' + ', '.join(f'0x{b:02x}' for b in chunk))
    array_body = ',\n'.join(rows)

    header = (
        '#pragma once\n'
        '// ============================================================\n'
        f'//  {os.path.basename(dst_path)}  —  auto-generated\n'
        '//  DO NOT EDIT THIS FILE DIRECTLY.\n'
        f'//  Source   : {os.path.basename(src_path)}  ({orig_kb:.1f} KB)\n'
        f'//  Minified : {mini_kb:.1f} KB\n'
        f'//  Gzipped  : {gz_kb:.1f} KB  (saved {saved_pct}%)\n'
        '//\n'
        '//  Edit source HTML, then run:  python tools/build_web_ui.py\n'
        '//  Windows shortcut         :  tools\\build_web_ui.bat\n'
        '// ============================================================\n\n'
        f'static const uint8_t  {array_name}[] PROGMEM = {{\n'
        f'{array_body}\n'
        f'}};\n\n'
        f'static const uint32_t {len_name} = sizeof({array_name});\n'
    )

    with open(dst_path, 'w', encoding='utf-8') as f:
        f.write(header)

    print(f'  {os.path.basename(src_path):20s}  '
          f'{orig_kb:5.1f} KB  →  {gz_kb:4.1f} KB gzip  (saved {saved_pct}%)'
          f'  →  {os.path.basename(dst_path)}')


# ── Entry point ───────────────────────────────────────────────────────────────
def main():
    print('build_web_ui.py — minify + gzip HTML files\n')
    build_one(
        src_path   = os.path.join(PROJECT_DIR, 'web_ui.html'),
        dst_path   = os.path.join(PROJECT_DIR, 'web_ui.h'),
        array_name = 'WEB_HTML_GZ',
        len_name   = 'WEB_HTML_GZ_LEN',
    )
    build_one(
        src_path   = os.path.join(PROJECT_DIR, 'ap_setup.html'),
        dst_path   = os.path.join(PROJECT_DIR, 'ap_setup.h'),
        array_name = 'AP_SETUP_HTML_GZ',
        len_name   = 'AP_SETUP_HTML_GZ_LEN',
    )
    print('\nDone — now compile in Arduino IDE.')


if __name__ == '__main__':
    main()
